server:
  port: 8082

spring:
  application:
    name: microservice-email

  data:
    mongodb:
      host: localhost
      port: 27017
      database: email-service
      username: admin
      password: admin@admin