server:
  port: 8087

spring:
  application:
    name: microservice-email

  data:
    mongodb:
      username: root
      password: root-root
      port: 27017
      database: email-service
      host: localhost
      authentication-database: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  auth:
    name: auth
    url: http://localhost:8080